name: Reference Access Key

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update Config
        run: echo "journalring_access_key: ${{ secrets.JOURNALRING_ACCESS_KEY }}" > temp_config.toml
      - name: Append Config
        run: cat temp_config.toml >> config.toml
      - name: Clean up
        run: rm temp_config.toml
