name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update Config
        run: echo "journalring_access_key: ${{ secrets.JOURNALRING_ACCESS_KEY }}" >> config.toml