name: Deploy to neocities
on:
  push:
    branches:
      - main
concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public